spring.application.name=rule-manager

server.port=8083

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.10.101:3306/linda-mall-rt?useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.username=root
spring.datasource.password=15255862931zhu

spring.thymeleaf.cache=false